# Generated by Django 3.2.14 on 2022-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grade_easy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='grade_hard',
        ),
        migrations.RemoveField(
            model_name='post',
            name='grade_moderate',
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
